export type CatalogCategory = {
  name: string;
  icon: string;
};

export const CATALOG_CATEGORIES: CatalogCategory[] = [
  { name: "Apparel & Accessories", icon: "👗" },
  { name: "Consumer Electronics", icon: "🎧" },
  { name: "Sports & Entertainment", icon: "🏸" },
  { name: "Home & Garden", icon: "☕" },
  { name: "Agriculture, Food & Beverage", icon: "🍓" },
  { name: "Beauty", icon: "💄" },
  { name: "Commercial Equipment", icon: "🏭" },
  { name: "Construction & Building Machinery", icon: "🚜" },
  { name: "Construction & Real Estate", icon: "🏗️" },
  { name: "Electrical Equipment & Supplies", icon: "🔌" },
  { name: "Electronic Components", icon: "🔋" },
  { name: "Fabrication Services", icon: "⚙️" },
  { name: "Gifts & Crafts", icon: "🎁" },
  { name: "Home Appliances", icon: "🫖" },
  { name: "Health & Medical", icon: "🩺" },
  { name: "Industrial Machinery", icon: "🧰" },
  { name: "Jewelry, Eyewear & Watches", icon: "💍" },
  { name: "Furniture", icon: "🪑" },
  { name: "Lights & Lighting", icon: "💡" },
  { name: "Luggage, Bags & Cases", icon: "👜" },
  { name: "Material Handling", icon: "📦" },
  { name: "Personal Care & Home Care", icon: "🧴" },
  { name: "Parents, Kids & Toys", icon: "🧸" },
  { name: "Renewable Energy", icon: "🔋" },
  { name: "Packaging & Printing", icon: "📦" },
  { name: "Raw Materials", icon: "🪨" },
  { name: "Safety & Security", icon: "🔒" },
  { name: "School & Office Supplies", icon: "📎" },
  { name: "Shoes & Accessories", icon: "👟" },
  { name: "Service", icon: "🛎️" },
  { name: "Sportswear & Outdoor Apparel", icon: "🧥" },
  { name: "Tools & Hardware", icon: "🛠️" },
  { name: "Testing Instruments & Equipment", icon: "🔬" },
  { name: "Power Transmission", icon: "⚙️" },
  { name: "Vehicles & Transportation", icon: "🚚" },
  { name: "Vehicle Accessories, Electronics & Tools", icon: "🛞" },
  { name: "Vehicle Parts & Accessories", icon: "🚗" },
  { name: "Pet Supplies", icon: "🐾" },
];
